# Allocate additional memory to the Gradle JVM. The default is often not enough to decompile Minecraft.
org.gradle.jvmargs=-Xmx2G

# Various flags to optimize Gradle performance.
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configureondemand=true

# Enable all Gradle warnings
org.gradle.warning.mode=all

# Mod Metadata
group=dev.mattidragon
user=Modfest
slug=DemoBox
modrinthId=b2SVO5sB
modId=demobox
modName=DemoBox
modDescription=A tool for creating interactive demo environments for mods
authors=MattiDragon
contributors=
license=MIT
# Mod Version
modVersion=1.3.0
# Branch Metadata
branchName=26.1
compatibleVersions=26.1
compatibleLoaders=fabric
