name: Release

on:
  release:
    types:
      - published

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true

      - name: Build with Gradle
        run: ./gradlew build

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'build/libs/*.jar, !build/libs/*-sources.jar'

      - name: Upload GitHub release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/libs/*.jar;!build/libs/*-sources.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Modrinth
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ github.event.release.body }}

      - name: Sync README
        run: ./gradlew modrinthSyncBody
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
